name: Scope Gradle JDK v1.8
on: [push]

jobs:
  scope:
    runs-on: ubuntu-latest
    steps:
      - name: Check if SCOPE_APIKEY is set
        run: if [ "${{secrets.SCOPE_APIKEY}}" = "" ]; then exit 1; fi
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Test with Gradle
        run: ./gradlew clean test
        env:
          SCOPE_APIKEY: ${{secrets.SCOPE_APIKEY}}
